config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "accounts"

  root to: "pages#home"
  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  # --- relations ---
  belongs_to :company

  # --- validations ---
  validates :name, presence: true

  # --- scopes ---

  scope :ordered_newest, -> { order(id: :desc) }

  # --- callbacks ---

  # OPTION 1

  # after_create_commit -> {
  #   broadcast_prepend_to(
  #     "quotes", #stream channel
  #     partial: "quotes/quote", locals: { quote: self } # what will be inserted?
  #     target: "quotes" # which turbo_trame?
  #   )
  # }

  # OPTION 2

  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_update_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }

  #OPTION 3

  broadcasts_to ->(quote) { [quote.company, "quotes"] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  VALID_PASSWORD_REGEXP = /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}\z/

  # --- RELATIONSHIP
  devise :database_authenticatable, :registerable, :recoverable
  belongs_to :company

  # --- VALIDATIONS
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 8 },
                       format: { with: VALID_PASSWORD_REGEXP, message: "must contains least one(number, lower case, capital letter)" },
                       confirmation: true

  # --- METHODS
  def name #decorator?
    "@#{email.split("@").first.split("+").first.downcase}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?
  helper_method :current_company

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

	def home
	end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  def index
    @quotes = current_company.quotes.ordered_newest
  end

  # GET /quotes/:id
  def show; end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end
  
  # POST /quotes/
  def create
    @quote = current_company.quotes.new(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quote successfully created."}
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quote successfully updated."}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @quote.destroy
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote successfully destroyed." }
        format.turbo_stream { flash.now[:notice] = "Quote successfully destroyed."}
      end
    else
      render quotes_path, status: :unprocessable_entity
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message <%=flash_type%>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer_container">
  <p class="footer_container--description">
    Quotes App inspired in Hotrails tutorial, developed by <b>Marco Poggi</b>.
  </p>
  <ul class="footer_container--social">
    <li class="footer_container--social-item">
      <a href="https://github.com/MarcoPoggi" target="_blank" rel="noopener noreferrer"><%= image_tag "github-icon.svg", class:"social-item-image"%></a>
    </li>
    <li class="footer_container--social-item">
      <a href="https://www.linkedin.com/in/marcopoggi-dev/" target="_blank" rel="noopener noreferrer"><%= image_tag "linkedin-icon.svg", class:"social-item-image"%></a>
    </li>
  </ul>
</footer>

app/views/layouts/_navbar.html.erb
<header class="navbar_container">
  <% if user_signed_in? %>
    <div class="navbar_container--brand">
      <img src="https://www.freeiconspng.com/uploads/pepsi-logo-png-transparent-31.png" alt="<%=current_company.name%> brand">
      <%= link_to current_company.name, root_path, class:"brand-name" %>
    </div>
    <div class="navbar_container--right_bar">
      <div class="navbar_container--username">
        <span><%= current_user.name %></span>
      </div>
      <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "navbar_container--button-link" %>
    </div>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "navbar_container--button-link" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div id="root">
      <%= render "layouts/navbar" %>
      <div id="flash" class="flash">
        <%= render "layouts/flash" %>
      </div>
      <div class="main_content">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<main class="home_page">
  <h1 class="home_page--title">Quote editor</h1>
  <p class="home_page--text">A blazing fast quote editor built with Hotwire</p>
  <% if user_signed_in? %>
    <%= link_to "View quotes", quotes_path, class:"home_page--link button-link" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class:"home_page--link button-link" %>
  <% end %>
</main>

app/views/quotes/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <h3> You don't have any quotes </h3>
  
  <%= link_to "Add quote",  new_quote_path, data: {
    turbo_frame: dom_id(Quote.new)
  } %>
</div>

app/views/quotes/_form.html.erb
<%= form_with model:quote do |f| %>
  <% if quote.errors.any? %>
    <div>
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>
  <%= f.text_field :name, input_html: { autofocus: true, placeholder: :name } %>
  <%= link_to "Cancel", quotes_path %>
  <%= f.submit %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag dom_id(quote), class: "turbo_tag" do%>
  <div class="quote_badge">
    <%= link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" }, class:"quote_badge--name" %>
    <div class="quote_badge--actions">
      <%= button_to quote_path(quote), method: :delete, class:"quote_badge--actions_delete_btn" do %>
        <span class="material-symbols-outlined icon-btn">delete</span>
      <%end%>
      <%= link_to edit_quote_path(quote), class:"quote_badge--actions_edit_btn" do %>
        <span class="material-symbols-outlined icon-btn">edit_note</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@quote) %>

app/views/quotes/edit.html.erb
<main>
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>
  <div>
    <h1>Edit quote</h1>
  </div>
  <%= turbo_frame_tag dom_id(@quote) do %>
    <%= render "form", quote: @quote %>
  <% end%>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from(current_company, "quotes") %>
<main class="quotes_container">
  <header class="quotes_container--header">
    <h1>Quotes</h1>
    <%= link_to "New quote", new_quote_path, data: {turbo_frame: dom_id(Quote.new)}, class: "button-link"%>
  </header>
  <%= turbo_frame_tag dom_id(Quote.new)%>
  <%= turbo_frame_tag "quotes", class:"quotes_container--content" do %>
    <%= render "quotes/empty_state" %>
    <%= render @quotes %>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main>
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div>
    <h1>New quote</h1>
  </div>
  <%= turbo_frame_tag dom_id(@quote) do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main>
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div>
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main> 

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.update @quote %>
<%= render_turbo_stream_flash_messages %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <span class="error_explanation--message"><%= resource.errors.full_messages.first%></span>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"button-link-secondary"%><br />
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>